services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'

  node-exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'

  cadvisor:
    image: google/cadvisor:latest
    container_name: cadvisor
    ports:
      - "8080:8080"
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana-storage:/var/lib/grafana

  bitcoin-exporter-node0:
    image: jvstein/bitcoin-prometheus-exporter
    container_name: bitcoin-exporter-node1
    environment:
      BITCOIN_HOST: bitcoind-node1
      BITCOIN_PORT: [your-bitcoind-rpcport]
      BITCOIN_USER: [your-rpcuser]
      BITCOIN_PASSWORD: [your-rpcpassword]
    ports:
      - "8334:8334" # Change the port for each node to avoid conflict

  bitcoin-exporter-node1:
    image: jvstein/bitcoin-prometheus-exporter
    container_name: bitcoin-exporter-node1
    environment:
      BITCOIN_HOST: bitcoind-node1
      BITCOIN_PORT: [your-bitcoind-rpcport]
      BITCOIN_USER: [your-rpcuser]
      BITCOIN_PASSWORD: [your-rpcpassword]
    ports:
      - "8334:8334" # Change the port for each node to avoid conflict

  bitcoin-exporter-node2:
    image: jvstein/bitcoin-prometheus-exporter
    container_name: bitcoin-exporter-node1
    environment:
      BITCOIN_HOST: bitcoind-node1
      BITCOIN_PORT: [your-bitcoind-rpcport]
      BITCOIN_USER: [your-rpcuser]
      BITCOIN_PASSWORD: [your-rpcpassword]
    ports:
      - "8334:8334" # Change the port for each node to avoid conflict

  bitcoin-exporter-node2:
    image: jvstein/bitcoin-prometheus-exporter
    container_name: bitcoin-exporter-node1
    environment:
      BITCOIN_HOST: bitcoind-node1
      BITCOIN_PORT: [your-bitcoind-rpcport]
      BITCOIN_USER: [your-rpcuser]
      BITCOIN_PASSWORD: [your-rpcpassword]
    ports:
      - "8334:8334" # Change the port for each node to avoid conflict

  bitcoin-node-0:
    build:
      args:
        ARCH: x86_64
        BITCOIN_URL: https://bitcoincore.org/bin/bitcoin-core-24.0/bitcoin-24.0-x86_64-linux-gnu.tar.gz
        BITCOIN_VERSION: '24.0'
      context: .
      dockerfile: Dockerfile
    container_name: warnet_0
    volumes:
    - ./config/bitcoin.conf:/root/.bitcoin/bitcoin.conf
  bitcoin-node-1:
    build:
      args:
        ARCH: x86_64
        BITCOIN_URL: https://bitcoincore.org/bin/bitcoin-core-24.1/bitcoin-24.1-x86_64-linux-gnu.tar.gz
        BITCOIN_VERSION: '24.1'
      context: .
      dockerfile: Dockerfile
    container_name: warnet_1
    volumes:
    - ./config/bitcoin.conf:/root/.bitcoin/bitcoin.conf
  bitcoin-node-2:
    build:
      args:
        ARCH: x86_64
        BITCOIN_URL: https://bitcoincore.org/bin/bitcoin-core-25.0/bitcoin-25.0-x86_64-linux-gnu.tar.gz
        BITCOIN_VERSION: '25.0'
      context: .
      dockerfile: Dockerfile
    container_name: warnet_2
    volumes:
    - ./config/bitcoin.conf:/root/.bitcoin/bitcoin.conf
  bitcoin-node-3:
    build:
      args:
        ARCH: x86_64
        BITCOIN_URL: https://bitcoincore.org/bin/bitcoin-core-25.0/bitcoin-25.0-x86_64-linux-gnu.tar.gz
        BITCOIN_VERSION: '25.0'
      context: .
      dockerfile: Dockerfile
    container_name: warnet_3
    volumes:
    - ./config/bitcoin.conf:/root/.bitcoin/bitcoin.conf
volumes:
  grafana-storage:
version: '3.8'
